antora:
  extensions:
  - require: '@springio/antora-extensions'
    root_component_name: 'modulith'
site:
  title: Spring Modulith
  url: https://docs.spring.io/spring-modulith/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: https://github.com/spring-projects/spring-modulith
    # Refname matching:
    # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
    branches: [main,'({1..9}).+({0..9}).x', '!(1.0.x)']
    tags: ['({1..9}).+({0..9}).+({0..9})?(-{RC,M}+({0..9}))', '!(1.0.+({0..9})?(-{RC,M}+({0..9})))']
    start_path: src/docs/antora
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    kroki-fetch-diagram: true
  extensions:
  - '@springio/asciidoctor-extensions'
  - '@asciidoctor/tabs'
  - asciidoctor-kroki
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.13/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
    format: pretty
